FROM bondvet/circle-ci:18.18.2

ARG BALENA_VERSION=17.4.4

RUN cd /tmp \
  && wget "https://github.com/balena-io/balena-cli/releases/download/v${BALENA_VERSION}/balena-cli-v${BALENA_VERSION}-linux-x64-standalone.zip" -O balena-cli.zip \
  && unzip balena-cli.zip \
  && sudo mkdir -p /usr/local/lib \
  && sudo mv balena-cli /usr/local/lib/ \
  # cleanup
  && sudo rm -rf /tmp/*

ENV PATH="/usr/local/lib/balena-cli:${PATH}"

