FROM bondvet/circle-ci:20.19.0

ARG BALENA_VERSION=22.5.5

RUN cd /tmp \
  && wget "https://github.com/balena-io/balena-cli/releases/download/v${BALENA_VERSION}/balena-cli-v${BALENA_VERSION}-linux-x64-standalone.tar.gz" -O balena-cli.tar.gz \
  && tar -xzf balena-cli.tar.gz \
  && sudo mkdir -p /usr/local/lib \
  && sudo mv balena-cli /usr/local/lib/ \
  # cleanup
  && sudo rm -rf /tmp/*

ENV PATH="/usr/local/lib/balena-cli:${PATH}"

