FROM bondvet/circle-ci:v22.22.2

ARG BALENA_VERSION=22.5.5

RUN cd /tmp \
  && wget "https://github.com/balena-io/balena-cli/releases/download/v${BALENA_VERSION}/balena-cli-v${BALENA_VERSION}-linux-x64-standalone.tar.gz" -O balena.tar.gz \
  && tar -xzf balena.tar.gz \
  && sudo mkdir -p /usr/local/lib \
  && sudo mv balena /usr/local/lib/ \
  # cleanup
  && sudo rm -rf /tmp/*

ENV PATH="/usr/local/lib/balena/bin:${PATH}"

